config/routes.rb
MyCan::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "keys#new", :as => "sign_up"
  get "products/index"
  root :to=>'products#index'
  resources :products
  resources :users
  resources :sessions
  resources :keys

end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
     user ||= User.new # guest user (not logged in)
     if user.role=="admin"
       can :manage, :all
     elsif user.role=="guest"
       can :create, Product
       can [:update,:delete], Product, :user_id => user.id
     else
        can :read, :all  
       #can :manage, :all if user.role=="admin"
       #can :create, :all if user.role=="guest"
     end
  end
end

app/models/key.rb
class Key < ActiveRecord::Base
   before_save :authenticate_key

   attr_accessible :val

   def authenticate_key
      if val=="one"
          true
      else
          false
      end
   end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :user

  attr_accessible :title, :description, :price, :user_id

  validates_presence_of :title, :description, :price

  validates_uniqueness_of :title

  validates_length_of :title, :in=>4..10

  validates_length_of :description, :minimum=>10

  validates_numericality_of :price
end

app/models/user.rb
class User < ActiveRecord::Base
 
 has_many :products


 attr_accessible :username, :password, :password_confirmation, :role
   attr_accessor :password
   before_save :encrypt_password

   validates_confirmation_of :password
   validates_presence_of :password, :on => :create
   validates_presence_of :username
   validates_uniqueness_of :username

 ROLES=%w{admin guest}
  
   def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, :alert=>'Not authorised user'
  end

helper_method :current_user



private

 def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end

end   

app/controllers/keys_controller.rb
class KeysController < ApplicationController

  def new 
    @key=Key.new(:val => cookies[:key_va])
  end
 
  def create 
    @key=Key.new(params[:key])
    if @key.save
        cookies[:key_val]=@key.val
        redirect_to new_user_path
    else
        flash.now[:notice]='wrong key entered'
        render 'new'
    end
     
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

 before_filter :self_load, :only=>[:show,:edit,:update,:destroy]

 before_filter :authenticate_user, :only=>[:new, :edit,:update,:destroy]

authorize_resource :only=>[:create, :edit, :update,:delete]

   def index
    @products=Product.find(:all)
   end

   def new 
    @product=Product.new(:user_id=>current_user.id)
   end


   def create
     @product=Product.new(params[:product])
     if @product.save
        redirect_to root_url, :notice=>'New Product has been added'
     else
        render :action=>'new'
     
     end
   end  
 
   def show
   end

   def edit
   end
  
   def update
    if @product.update_attributes(params[:product])
       redirect_to root_url, :notice=>'Product has been updated.'
      else
         render :action => 'edit'
      end
   end

   
  def destroy
    @name=@product.title
    @product.destroy
    redirect_to root_url, :notice=>"#{@name} has been deleted"    
  end
 
  def self_load
    @product = Product.find(params[:id])
  end

  def authenticate_user
    if current_user
    else
       redirect_to root_url, :notice=>'You are not authorised to access'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
 end

def create
  user = User.authenticate(params[:username], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url
  else
    flash.now.alert = "Invalid username or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
   if cookies[:key_val]=="one"
     @user = User.new(:role=>"admin")
     cookies.delete(:key_val)
   else
     @user = User.new(:role=>"guest")
   end
  end

 def create
   @user = User.new(params[:user])
   if @user.save
     redirect_to root_url, :notice => "Signed up!"
   else
     render "new"
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/keys/new.html.erb
<p><b>To Sign up as Admin</b></p>
<%= form_for(@key) do |f| %>
 <%= f.label 'Enter Key:' %>
 <%= f.text_field :val %>
 <%= f.submit 'Enter' %>
<% end %>
<%= link_to 'Skip', new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
    Logged in as <%= current_user.username %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
<p><%= flash[:notice] if flash[:notice].present? %></p>
<p><%= flash[:alert] if flash[:alert].present? %></p>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h3> Edit </h3>
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<ul><% @product.errors.full_messages.each do |m| %>
<li><%= m %></li>
<% end %></ul>
<% end %>

<table>
   <tr><td><%= f.label 'Title:' %></td>
       <td><%= f.text_field :title %></td>

   <tr><td><%= f.label 'Description:' %></td>
	  <td><%= f.text_area :description,:rows=>10 %></td></tr>
   
   <tr><td><%= f.label 'Price:' %></td>
       <td><%= f.text_field :price %></td></tr>

   <tr><td><%= f.submit 'Save' %></td></tr>
</table>
<% end %>
<%= link_to 'Back', root_url %>

app/views/products/index.html.erb
<% if @products.blank? %>
  <h2> No products to display </h2>
  <% else %>
    <h2> List of Products </h2>
    <% @products.each do |product| %>
     <ul><li><p>
       <%= link_to product.title, product %>
       <% if can? :update, product %>
       <%= link_to 'Edit',{ :action=>'edit',:id=>product.id } %>
       <% end %>
       <% if can? :delete, product %>
       <%= link_to 'Delete', product, method: :delete, confirm: 'Are you sure?' %>
       <% end %>
     </p></li></ul>
  <% end %>
<% end %>

<% if can? :create, Product %>
<%= link_to 'Add Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h2> Add Product </h2>
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

<table>
   
   <tr><td><%= f.label 'Title:' %></td>
       <td><%= f.text_field :title %></td>

   <tr><td><%= f.label 'Description:' %></td>
	  <td><%= f.text_area :description,:rows=>10 %></td></tr>
   
   <tr><td><%= f.label 'Price:' %></td>
       <td><%= f.text_field :price %></td></tr>
 
   <tr><td><%= f.hidden_field :user_id %></td></tr>

   <tr><td><%= f.submit 'Save' %></td></tr>
</table>

<% end %>
<%= link_to 'Back', root_url %>

app/views/products/show.html.erb
<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Back', root_url %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.hidden_field :role %>

  <p><%= f.submit "Sign Up"%></p>
<% end %>